### PR TITLE
Update Android APK download link

### PR DESCRIPTION
**Pull request by incognitojam**
- Update the "Direct APK download" link to the latest version [4.0.0](https://github.com/langerhans/dogecoin-wallet-new/releases/tag/4.0.0)
- Replace Play Store badge with newer image
- Translate the contents of the anchor tag instead of the entire element (happy to revert this if it was intentional)

### CODE REVIEW

**Review by patricklodder — DISMISSED** [review]
Perfect! Thank you!

**Comment by tuckbick** [comment]
Does a localization need to be added for `fr`?

**Comment by incognitojam** [comment]
No `fr` translations exist for those keys, so there was nothing for me to update 😕 

Edit:
Specifically `dgc-android-wallet-modal-title` and `dgc-android-wallet-modal-apk` don't exist in `fr.json` (also looks like `dgc-ios-wallet-modal-title` is missing)

**Comment by tuckbick** [comment]
I don't speak French, but I gathered together some translations from other github projects which I think should work for this context:
```json
"dgc-android-wallet-modal-title": "TÉLÉCHARGER SUR GOOGLE PLAY.",
"dgc-android-wallet-modal-apk": "Téléchargement APK direct",
"dgc-ios-wallet-modal-title": "TÉLÉCHARGER SUR L'APP STORE",
```

**Comment by incognitojam** [comment]
I don't think this PR applies anymore since the direct download link has been removed in the new design

**Pull request closed without merging**
