### PR TITLE
Mobile browser enhancements

### PR DESCRIPTION
**Pull request by jwoglom**
Make the bar at the bottom appear at the bottom of the page if there is room, like a full-page responsive site

screen shot 2014-04-26 at 3 41 33 pm
screen shot 2014-04-26 at 3 41 39 pm

When there isn't room, have it default to it's previous behavior of appearing in place

screen shot 2014-04-26 at 3 41 50 pm

Fix the second video that, in mobile browsers where the width < 400px, was causing a scrollbar.

screen shot 2014-04-26 at 3 42 01 pm

Make the bottom buttons smaller and in a 2x2 grid layout when there is room.

screen shot 2014-04-26 at 3 42 10 pm

Add a padding at the bottom of the page so the footer is always visible over the share icons.

screen shot 2014-04-26 at 3 42 17 pm

### CODE REVIEW

**Comment by PowerLemons** [comment]
I'm testing it out right now, and I found a few problems with it.
First of all, on smaller resolutions, the scroll-down container covers up the contents above it.
http://puu.sh/8oyUR
You should definitely fix that.

Asides from that, the contents (Dogecoin title, Dogecoin photo, Download Section, y'know what I mean) look awkwardly positioned. It should be vertically aligned in the middle too.

The YouTube video resizing in this is unnecessary. There is already FitVids. I accidentally broke it when I introduced the Getting Started YouTube Video. The fix is in Pull Request https://github.com/dogecoin/dogecoin.com/pull/16.

These are the problems that I found with this pull request. 
I like how the page is more responsive, but please fix the problems first nonetheless.

**Comment by jwoglom** [comment]
Hi, thanks for the feedback -- a couple questions.
- I don't see the first issue you mentioned -- this is what I see in Chrome, Firefox, and Safari at the same dimensions (1069x559): 
  screen shot 2014-04-26 at 4 32 24 pm
- Control-tabbing between dogecoin.com and my changes, I can't see any differences pixel-by-pixel. So I'm not sure what you want me to do about that.
- I just committed removing the youtube video fix.
  Let me know if there's anything else I can do.

**Comment by PowerLemons** [comment]
It's not working on Internet Explorer.
This is an 800 x 600 screenshot for example on the latest version of Internet Explorer for Windows 7: http://puu.sh/8oCrL
Even though I hate it, a lot of people use Internet Explorer.

And you have to vertically center the contents above the scroll-down container. It looks really bad on 1080p: http://i.imgur.com/8bWiHG4.png

**Comment by jwoglom** [comment]
Ok, I think i've made it so it doesn't take up the whole page when the browser's height is over 1000px. And, because the code that triggers the arrow is now in a @media which IE doesn't support, it should look and act correctly now.

**Comment by PowerLemons** [comment]
Closing as it is old and unmergeable. If you wish to make a new pull request, please do so.

**Pull request closed without merging**
