### PR TITLE
Add Greek language

### PR DESCRIPTION
**Pull request by ir4klis**
### Description
Adding Greek translation for dogecoin.com

### CODE REVIEW

**Review by nick-vas — DISMISSED** [review]
It's all greek to me

**Comment by langerhans** [comment]
Hi thank you for this! To make the language available on the website you will need to additionally change a bit in the javascript and HTML files. See for reference here: https://github.com/dogecoin/dogecoin.com/pull/211/files#diff-3708caf1ae0a3f4f266bc2060af1279ef61b739abdf1f2cd852049252f40a09c Let me know if I should do that instead, but would appreciate if you'd complete the PR this way :)

**Comment by ir4klis** [comment]
> Hi thank you for this! To make the language available on the website you will need to additionally change a bit in the javascript and HTML files. See for reference here: https://github.com/dogecoin/dogecoin.com/pull/211/files#diff-3708caf1ae0a3f4f266bc2060af1279ef61b739abdf1f2cd852049252f40a09c Let me know if I should do that instead, but would appreciate if you'd complete the PR this way :)

Is this OK?

**Comment by ir4klis** [comment]
@langerhans  Hi I made the changes a while ago would you check it please.

Regards :)

**Review by e-me — APPROVED** [review]

**Pull request closed without merging**
