### PR TITLE
Optimized & updated proposition 

### PR DESCRIPTION
**Pull request by FlipFloop**
Here is a refresh of the site.

All images were losslessly optimized, the main .js files minified, and the .css files minified. 

Bottom links were added to the Reddit and Github pages.

Readability was increased for the links in the body part of the site, and small color transitions given to the buttons.

### CODE REVIEW

**Comment by freelancing-solutions** [comment]
Why cant we just rewrite the entire site using react.js

**Comment by arpitparmar5739** [comment]
> Why cant we just rewrite the entire site using react.js

I was thinking the same thing. Let's collaborate.

**Comment by nickatnight** [comment]
@freelancing-solutions @arpitparmar5739 any update on the React progress?

**Comment by arpitparmar5739** [comment]
> @freelancing-solutions @arpitparmar5739 any update on the React progress?

RIP Dogecoin webpage in React ;P, Shifted to learning Linux Kernel Development currently.

**Pull request closed without merging**
