### PR TITLE
Organized Classes, Dogecoin Video tweak, Container Colors, and other tiny changes.

### PR DESCRIPTION
**Pull request by PowerLemons**
This Pull Request has many changes. This pull request modifies the following:

**Markup**
- Replaces the hard-coded style attributes in the HTML index document with CSS Classes.
- Removed extra period typo in meta description.
- Double slash URLs for CDNs without them.
- See how the What is Dogecoin video on http://dogecoin.com/ moves the website slightly when you click the button? This fixes it.

**Design**
- Removes bold on "DOGECOIN" title in header, made font size bigger to accommodate for it. This is so it isn't "pixelly" on computer displays.
- More saturated info container colors.
- Removed top-border on bottom bar in header.
- Centered Dogecoin logo in header a bit.
- Adds some padding to circle buttons when on mobile. [Before](http://puu.sh/9BaVb/44b1a6e28f.png) and [After](http://puu.sh/9BaSC/7bcadeaf45.png).
- Capitalized credits on bottom of page (the lowercase letters doesn't fit the rest of the website!).

Preview: http://i.imgur.com/g5cZv6e.png
After pressing YouTube video (notice the header container not moving?): http://i.imgur.com/rwU9urk.png

### CODE REVIEW

**Comment by ummjackson** [comment]
@PowerLemons Giving you access to make direct edits to the site. With great power comes great responsibility, but I trust that you'll exercise this wisely :)

**Comment by DomT4** [comment]
Surely, Many Power, Such Responsibility? ;). Good to see you still around here Jackson, in all seriousness.

**Comment by PowerLemons** [comment]
@ummjackson Sounds great! It seems I do not have that power on Dogecoin.com currently though, so maybe you could enable it =)? So thanks, very appreciate.

**Comment by ummjackson** [comment]
Should be all sorted now @PowerLemons :+1: Thanks again for all the hard work you do. 

@DomT4 Thanks for the kind words, I'm definitely around :)

**Pull request merged**
