### PR TITLE
Not sure?

### PR DESCRIPTION
**Pull request by gregcron**
I'm really not sure how to use GitHub... there's a request below -- hopefully someone can see it and let me know how to best make my request.

### CODE REVIEW

**Comment by gregcron** [comment]
+Ok apologies, I have never used GitHub, but upon reaching out to Jackson, he requested I make a request here in GitHub.
+
+I'd like to propose that weselldoges.com be included on Dogecoin.com as a way to obtain Dogecoin. One of the biggest
+barriers to entry for newcomers is obtaining (buying) Dogecoin. People new to cryptos aren't familiar enough with
+exchanges and get confused when instructed to buy Bitcoin from Coinbase/etc., send to Cryptsy/etc., trade for Doge, and
+so on.
+
+WeSellDoges.com is as simple as checking out via PayPal. We have sold more than 1 BILLION Dogecoin since opening in April.
+
+I'd encourage and appreciate consideration of including it somewhere on Dogecoin.com for "how to get Doge".
+
+Thanks,
+Greg
+support@weselldoges.com

**Comment by PowerLemons** [comment]
I will add WeSellDoges in the Get Dogecoin section of the website later this week, most likely on the weekend. Your service is a great for Dogecoin - offering an easy way for newcomers to be introduced to our coin.

By the way, nice website. I wonder who made it!

**Comment by DomT4** [comment]
I was just about to start working on creating a PR to add WSD to the Get Dogecoin section. I'll hold off if PowerLemons is going to do so. Happy to chat with you on how to create PRs & such if you desire @gregcron.

**Comment by gregcron** [comment]
Thanks guys!  Sure dominyk ; that'd be great -- I had no clue what I was
doing in github so glad it ended up being seen :)

And thanks PowerLemons :) design's been great

**Comment by DomT4** [comment]
Github themselves have got great tutorials, [this one](https://help.github.com/articles/fork-a-repo) on the fork process, and [this one](https://help.github.com/articles/using-pull-requests) cover the two aspects you would've needed here to 'propose' this change. If you have any questions or queries, feel free to hit me up by email, which you can find [here](https://pgp.mit.edu/pks/lookup?op=vindex&search=0x872524DB9D74326C).

**Comment by PowerLemons** [comment]
It took a bit longer than I expected, but I've added WeSellDoges.
PR closed, thank you very much for supporting Dogecoin.com.

**Comment by gregcron** [comment]
Thanks !!

**Pull request closed without merging**
