### PR TITLE
Add link to Windows Phone wallet app

### PR DESCRIPTION
**Pull request by cr5315**
reddit user [/u/Zumicts](http://www.reddit.com/user/Zumicts) made a Windows Phone app that uses DogeAPI.

Found in [this post to /r/dogecoin](http://www.reddit.com/r/dogecoin/comments/29dmug/reposting_from_rwindowsphone_a_mobile_wallet_for/)

[Preview here](http://cr5315.com/dogecoin/)

### CODE REVIEW

**Comment by PowerLemons** [comment]
Same as the iOS wallet DogeKeeper, as far as I know this app isn't open-source. This means that it opens the possibility for the app developer to steal people's account information and their coins unless the code is open for everyone to review. Not saying the app developer will definitely do this, but again this is a possibility.

**Comment by haroldma-zz** [comment]
I am the app developer.  Ill be willing to post the project as open source under the MIT license.

**Comment by haroldma-zz** [comment]
I have made the project open source: https://github.com/Zumicts/DogeMuch

**Comment by PowerLemons** [comment]
Closed as @Zumicts PR already serves the same purpose. Also, it is automatically mergeable.

**Comment by cr5315** [comment]
I'm not sure what I did to make the merge conflicts. Probably EOL markers, dern Windows.

**Pull request closed without merging**
