### PR TITLE
Fixed French json

### PR DESCRIPTION
**Pull request by AstroOrbis**
### Description
Just making some urgent changes to the fr.json :)

### Motivation and Context
I volunteered to do this in dogecoin/dogecoin#1887

### How Has This Been Tested?
No testing needed due to this PR just changing text in the JSON file.
### Checklist:

- [X] GitHub issue linked
- [X] The necessary translations have been added for all languages
- [X] Any documentation has been updated accordingly
- [X] Responsive sizes (Mobile) tested
- [X] Cross Browser tested if necessary
- [X] Conflicts resolved

### CODE REVIEW

**Comment by AstroOrbis** [comment]
Please do not merge this yet! There are still changes to be made.

**Comment by Luca-Ziesler** [comment]
Since you're only really changing text shouldn't it already be "responsive for mobile"?

**Comment by NobodyFAH** [comment]
Since you're only really changing the text shouldn't it already be "responsive for mobile"?

**Comment by AstroOrbis** [comment]
Good point, editing that now.

**Comment by AstroOrbis** [comment]
The most urgent fixes have been made, so it should be ready to merge. I’ll make more changes later.

**Review by langerhans — APPROVED** [review]

**Comment by langerhans** [comment]
Thank you!

**Comment by NobodyFAH** [comment]
Thank you very much

**Comment by AstroOrbis** [comment]
You're welcome! Anytime :)

**Pull request merged**
