### PR TITLE
Create es.json

### PR DESCRIPTION
**Pull request by otamaglimmer**
I just made a full translation to spanish, I hope you find it useful.

### CODE REVIEW

**Comment by dhpollack** [comment]
When you use quotes, you need to escape them.  for example on line 145, you have not escaped the quotes around ligero.

**Comment by PowerLemons** [comment]
Merged. Thank you very much for the translation, we all appreciate it!

**Comment by dhpollack** [comment]
@otamaglimmer @PowerLemons This should not have been merged.  It is not valid json.

Go to jsonlint.com and try to copy and paste this file and you can see your errors.  This is why it doesn't work on [dogecoin.com/?lng=es](http://www.dogecoin.com/?lng=es) as expected.

**Comment by PowerLemons** [comment]
@dhpollack It has been fixed. Thanks for bringing that site to my attention.

**Comment by otamaglimmer** [comment]
Sorry for the errors. As I said, is my first time submitting a pull request and using json files.
I'm glad to help.

I've looked around in dogecoin.com/?lng=es and everything looks great, but I have a question:
The http://dogecoin.com/getting-started link is not going to the spanish translation, I have to manually add ?lng=es at the end. Is this an issue on my side?

**Comment by PowerLemons** [comment]
@otamaglimmer [It's working for me](http://puu.sh/hGkme/0d62041500.png). Try loading it again.

**Comment by otamaglimmer** [comment]
Yes, it works fine, but the link in the front page to the "Getting Started" section leads to the english getting started guide, instead of the spanish one.
http://i.imgur.com/dqyZOpE.png

**Pull request merged**
