### PR TITLE
feat: generate copyright year from inline js [#152]

### PR DESCRIPTION
**Pull request by nickatnight**
### Description
See ticket #152 

### Motivation and Context
See above

### How Has This Been Tested?
Tested by viewing page in browser locally

### Screenshots (if appropriate):
Screen Shot 2021-04-12 at 3 32 13 PM

### Checklist:

- [x] GitHub issue linked
- [x] The necessary translations have been added for all languages
- [x] Any documentation has been updated accordingly
- [x] Responsive sizes (Mobile) tested
- [x] Cross Browser tested if necessary
- [x] Conflicts resolved

### CODE REVIEW

**Comment by patricklodder** [comment]
marking as draft pending a clarification re: can we do this.

**Comment by freelancing-solutions** [comment]
generating a year based on the users system date falls victim to when then user date settings are not set correctly....
i solved this by using a time api to base the date on est time see pull request .

[165](https://github.com/dogecoin/dogecoin.com/pull/165)

This solves the issue of dynamic copyright year without falling victim to wrong clock settings.

**Review by SeptBlast — DISMISSED** [review]

**Comment by nickatnight** [comment]
My branch needs to be synced and added year support for additional pages

**Comment by nickatnight** [comment]
@SeptBlast added js to support/guide pages and marked pr ready for review

Edit:

>marking as draft pending a clarification re: can we do this.

Assuming we can do this

**Review by langerhans — APPROVED** [review]
Looking into this this seems common practice, so I'll go ahead and approve this from my side.

**Review by aarsxx — APPROVED** [review]

**Comment by nickatnight** [comment]
@langerhans @rnicoll can we merge this ticket in? Site currently displays 2021 instead of 2022. This fix eliminates need for year to be managed by developer. See image below
Screen Shot 2022-01-04 at 1 10 48 PM

**Comment by rnicoll** [comment]
I thought copyright applied when a file was changed, not entirely sure if this is correct (or at least I wonder if we can do it when we generate the static files)

**Pull request closed without merging**
