### PR TITLE
Translate to Simplified Chinese 

### PR DESCRIPTION
**Pull request by aohas**
Adding Chinese translation to the website
增加网站的中文翻译

### CODE REVIEW

**Comment by DodoShen** [comment]
I could help with tranditional Chinese.

**Comment by bobdos** [comment]
I can help to review the Simplified Chinese one.

**Comment by rnicoll** [comment]
Please note this is a translation of the very old website. If someone can use this as a base but update against the latest website version, it would be appreciated.

**Comment by bobdos** [comment]
> Please note this is a translation of the very old website. If someone can use this as a base but update against the latest website version, it would be appreciated.

Got it, @rnicoll 

So, should we submit a total new pull request, or update this pull request directly?

**Comment by rnicoll** [comment]
If the original author isn't around, probably easiest to make a new PR. If you rebase the original commit they'll still get credit for their work, and then it's just updating it to the new site content

**Comment by hao6yu** [comment]
> > Please note this is a translation of the very old website. If someone can use this as a base but update against the latest website version, it would be appreciated.
> 
> Got it, @rnicoll
> 
> So, should we submit a total new pull request, or update this pull request directly?

@bobdos 
hey man, are you currently working on this one? if not, I'd like to help :)

**Comment by bobdos** [comment]
> If the original author isn't around, probably easiest to make a new PR. If you rebase the original commit they'll still get credit for their work, and then it's just updating it to the new site content

Got it @rnicoll I shall open a new pull request soon, easier to follow the latest site info, to avoid distraction if based on the old ones.

**Comment by langerhans** [comment]
Closing in favor of #227

**Pull request closed without merging**
