### PR TITLE
French translation 

### PR DESCRIPTION
**Pull request by mxthys**
### Description
I can translate in French 
### Motivation and Context
Because you did a tweet to find people to help to translate the page

### How Has This Been Tested?

 just translate. 

### Checklist:

- [ ] GitHub issue linked
- [x] The necessary translations have been added for all languages
- [ ] Any documentation has been updated accordingly
- [ ] Responsive sizes (Mobile) tested
- [ ] Cross Browser tested if necessary
- [ ] Conflicts resolved

### CODE REVIEW

**Comment by langerhans** [comment]
This branch needs a rebase. Make sure you create your branch from the latest commit on gh-pages or you'll pull all kinds of unrelated changes in as visible above. Thanks for the contribution though :)

**Comment by mxthys** [comment]
I'm not sure to understand what i have to do. Do i need to know how to code ?

**Comment by langerhans** [comment]
I'm trying to find the actual changes you did 😅 We have a French translation already, so did you add to it or made changes? When you did that, did you make them here on GitHub? In theory on the changes to fr.json are relevant.

**Comment by mxthys** [comment]
Ho okay, I haven't changed anything, I'm a little lost on how github works 😓

**Comment by langerhans** [comment]
So if you go to this file: https://github.com/dogecoin/dogecoin.com/blob/gh-pages/assets/i18n/fr.json You can see the current French translation. If you think anything could be improved feel free to change the file accordingly and then we can work on getting the changes on the website :)

**Comment by mxthys** [comment]
ok thanks for your help!

**Comment by mxthys** [comment]
I did a suggestion to one of Line 18
(Edit : I see that I don't need to notify it)

**Comment by langerhans** [comment]
Hey, someone else was also working on French translation in #188 maybe you can see if you want to suggest more changes there :)

**Comment by AstroOrbis** [comment]
It’s mostly grammatical and syntax errors, I’ll fix more soon but my PR is ready to merge!

**Review by inov84business — APPROVED** [review]

**Comment by langerhans** [comment]
I'm going to close this for now. If there are still improvements needed, please open a fresh PR as this one is pretty borked 😅

**Pull request closed without merging**
