### PR TITLE
added marathi translation

### LINKED ISSUE #187: Add marathi language (code: mr) translation
### Feature Description
Add translation for the Marathi language as Marathi is the most spoken language in India 

### Alternatives
No alternative

### PR DESCRIPTION
**Pull request by vj-codes**
### Description
Partially added Marathi translation, will be completed tomorrow :)
And removed a repetitive word from en.json

Fixes #187 

### Motivation and Context
Dogecoin is at its peak right now and would love to see my native language translated version for the website andd I love Dogecoin because of its beautiful community and simplicity
 
### How Has This Been Tested?
I Will add the tests after the translation is complete 

### Checklist:

- [ x] GitHub issue linked
- [ x] The necessary translations have been added for all languages

### CODE REVIEW

**Comment by vj-codes** [comment]
@langerhans hey can you review this please:)

**Comment by langerhans** [comment]
The changes look good, I can't review the phrases itself cause I don't speak the language :D The only thing I would probably change is the indentation in the js file so it lines up again with the rest of the file :) Also you would need to add the language to index.html 👍

**Comment by vj-codes** [comment]
@langerhans done!

**Review by langerhans — APPROVED** [review]

**Comment by langerhans** [comment]
Thank you!

**Comment by vj-codes** [comment]
@langerhans thank you!
Dogecoin to the moon 🚀

**Pull request merged**
