### PR TITLE
Tutorial update for iOS : MyDoge -> doughwallet

### PR DESCRIPTION
**Pull request by jflaloux**

### CODE REVIEW

**Comment by dhpollack** [comment]
you're going to need to update the translation files as well.

**Comment by jflaloux** [comment]
Thx @dhpollack, where are they located?

**Comment by PowerLemons** [comment]
@jflaloux The files are located in the [/i18n directory](https://github.com/dogecoin/dogecoin.com/tree/gh-pages/i18n).

For the first two steps, all you have to do is replace MyDoge with doughwallet. For the third step, get some shibes at /r/dogecoin to help translate it for you. I'll even give my approval if you send me the thread link.

**Comment by peoplma** [comment]
@PowerLemons I went ahead and posted a request for the translation to /r/dogecoin here:  http://redd.it/346ujn.  I'll make a PR to the i18n files if we get a good translation.

Edit: #82

**Comment by otamaglimmer** [comment]
Do you need / have spanish translations? I could take care of those.

**Comment by jflaloux** [comment]
@otamaglimmer Please, add it to the comments in the reddit thread.  
Thx a lot

**Comment by otamaglimmer** [comment]
I've just done a full translation of the en.json file. This is my first submission on github, so it's taking me some time to figure out how to do it correctly. This translation includes those 3 sentences, but I could post them in the reddit thread too.
Update: I've submitted a pull request. I hope it's ok.

**Comment by jflaloux** [comment]
Actually I think most of it was already translated.

Thanks a lot!

By the way, do we need all the languages to push the change?

**Comment by peoplma** [comment]
I believe PR #82 brings the rest of the languages up to date with the MYDOGE -> doughwallet change

**Comment by PowerLemons** [comment]
Merged. Thank you very much for this huge contribution.

**Pull request merged**
