### PR TITLE
Indonesian Translate

### PR DESCRIPTION
**Pull request by eiyu**
adjusting the slang that is not exist in Bahasa. I hope it's relatable. To the moooon!

### Checklist:

- [ ] GitHub issue linked
- [ ] The necessary translations have been added for all languages
- [ ] Any documentation has been updated accordingly
- [ ] Responsive sizes (Mobile) tested
- [ ] Cross Browser tested if necessary
- [ ] Conflicts resolved

### CODE REVIEW

**Comment by eiyu** [comment]
wow

**Comment by langerhans** [comment]
Hey, sorry but I can't merge this change. The Readme file does not support localization like the website so if we merge this we'd lose the English text for everyone else ;)

**Comment by langerhans** [comment]
Oh, someone actually added an Indonesian translation in #154 for the website as well :)

**Comment by eiyu** [comment]
No Problem,, good to hear someone already translated the website

**Pull request closed without merging**
