### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 3Samourai**

### CODE REVIEW

**Review by moritzebeling — APPROVED** [review]
Having the header section of the README centered would certainly look nice.

**Comment by CryptoTankGirl** [comment]
i appreciate the ability to understand these things on a forum such as this

**Review by CryptoTankGirl — APPROVED** [review]
great work

**Review by CryptoTankGirl — APPROVED** [review]
DO IT make this possible

**Comment by nickatnight** [comment]
@3Samourai please use PR template <3

**Pull request closed without merging**
