### PR TITLE
Introduce an FAQ

### PR DESCRIPTION
**Pull request by rnicoll**

### CODE REVIEW

**Comment by magneticat** [comment]
Hey Ross, this looks fine to me (I understand you must discuss the text with the other core devs, though)  - but we need to add the new footer with the language dropdown and wrap the text in the language tag so we can add translations!

I can help with this! But should I open another branch to do these edits? Just let me know!

**Comment by rnicoll** [comment]
@magneticat Can you raise a PR against my branch? That would be ideal. Thank you!

**Comment by magneticat** [comment]
Working on it!

**Comment by magneticat** [comment]
This should do it!

**Comment by rnicoll** [comment]
Rebased to resolve conflicts.

**Review by michilumin — APPROVED** [review]
All of this is good. And needed. I'm going to say go ahead and approve this but later on I want to add at least one FAQ line reiterating and emphasizing 'wallet.dat' being the key important file to back up, since I get questions about that all the time.

**Comment by rnicoll** [comment]
Raised https://github.com/dogecoin/dogecoin.com/pull/282 as follow-on PR.

**Pull request merged**
