### PR TITLE
chore: Add Code of Conduct

### PR DESCRIPTION
**Pull request by davidsonfellipe**
### Description
Proposal for default code of conduct for the project, based on https://www.contributor-covenant.org/version/2/0/code_of_conduct/

### Motivation and Context
Issue #166  

### How Has This Been Tested?
n/a

### Checklist:

- [x] GitHub issue linked
- [ ] The necessary translations have been added for all languages
- [ ] Any documentation has been updated accordingly
- [ ] Responsive sizes (Mobile) tested
- [ ] Cross Browser tested if necessary
- [x] Conflicts resolved

### CODE REVIEW

**Review by aarsxx — APPROVED** [review]
LGTM!

**Comment by comradekingu** [comment]
Professionalism and anti-humanism in the hands of "community leaders" wielding ultimate power always was and remains a mistake.

**Comment by tealethetoolman** [comment]
The recommended Code of Conduct seems to want to put the power into a central authority with a system of anonymous complaints for enforcement on things that are impossible on an immutable platform.
Blockchain is neither centralized or anonymous.

I feel like this could be a great idea on a centralized project, but for this, I'd like to see something that reflects our core tenants of why blockchain was created in the first place.

**Comment by comradekingu** [comment]
@tealethetoolman 
Don't know if I am one of us, but I did mine some Dogecoins on my openpandora when the project was new. (Least I think it was)

That would be _not_ a code of conduct then.
While also not a resulting code of conduct, sometimes they have a contact field.
There is no reason it couldn't feel welcoming, which is another quality that isn't pledging allegiance to authoritarianism.

Here is something from memory, which is more than can be said for the stuff people don't read, and can't remember or make sense of.

CONTACT.md

```
Welcome to the doge

Accept and give criticism constructively. \
Grant anyone their desired privacy. \
Resolve conflicts within these bounds.

Finding yourself unable, e-mail ____ the site admin.
```

**Review by aarsxx — APPROVED** [review]

**Comment by davidsonfellipe** [comment]
After reviewing the feedback on the proposed Code of Conduct, seems that is better to close the pull request for now. Thanks for reviewing.

**Pull request closed without merging**
