### PR TITLE
added CC 4.0 SA license

### PR DESCRIPTION
**Pull request by dhpollack**
The dogecoin.com website is not officially open sourced and therefore making and submitting changes to the site via github technically wouldn't be allowed and the owners could take legal action against those making improvements to the site.  I have brought up this issue twice ([#58](https://github.com/dogecoin/dogecoin.com/issues/58) and [#28](https://github.com/dogecoin/dogecoin.com/issues/28)), but nobody has responded.  Perhaps a better way is to simply create a pull request to open source the site and you can decide to merge it or not.

@ummjackson @langerhans @PowerLemons This is an important issue that has been ignored for a while now.  It's imperative that you as the legal owners of this site address this issue explicitly.

The reason being that as a contributor to dogecoin.com (internationalization code), I do not want to suddenly get sued by you or a subsequent owner because I helped make improvements to dogecoin.com even though it wasn't open source.

### CODE REVIEW

**Comment by dhpollack** [comment]
[http://dhpollack.github.io/](http://dhpollack.github.io/) for a preview of the change.

**Comment by DomT4** [comment]
Note that Creative Commons suggest people don't use their licenses for code. Design, sure, but for code they recommend people explore other options.

**Comment by PowerLemons** [comment]
I'm not knowledgable with anything law related, but it does make sense to open-source it from what you said. 

@ummjackson and @langerhans, what do you think about this PR?

**Comment by dhpollack** [comment]
@DomT4 yea, but is the site software or is it just design?  I consulted a few people and they suggested this.  But I also thought the MIT License was another idea.

@PowerLemons I'm not a lawyer either.  Technically, CC is used for content and something like the MIT License is used for code.  But we're in this wierd area in between, because although the site has some programming logic, I don't think it's considered software.  Since I felt this was more like content, I chose CC, but could always change the pull based on the discussion here.

**Comment by DomT4** [comment]
@dhpollack To be honest, It's murky and seems to be largely an individual website owner's desire. GNU cover all of their websites under a Creative Commons license. Bitcoin seem to cover their website under a whole bundle of open-source code licenses, including MIT & LGPL. Litecoin seem to use MIT. A lot of open-source websites just don't bother specifying the license at all. It's a frustratingly grey area.

**Comment by dhpollack** [comment]
@DomT4 Yup, I wasn't opposed to the MIT License.  But one thing that I don't want lost is that having no license is definitely a problem.

**Comment by DomT4** [comment]
@dhpollack Agreed, having the license displayed in a clear fashion protects contributors and the project, and is a logical step forwards. I suppose the license could always be split, with the code falling under MIT and the artwork under some form of Creative Commons license, if necessary. I have no objections to either MIT or CC, just wanted to have the debate a little on which form of license was most appropriate here.

**Comment by jwiechers** [comment]
@DomT4 Well, the artwork does not necessarily have to be released under Creative Commons unless the artists want to -- and in the case of the Dogecoin coin design I don't think it would be ideal because it would make some things more complicated. To rephrase: I'd advise against this most strongly.
The logos and mascots of open source projects generally are _not_ licensed under open licenses and this has _very good_ reasons, usually they're actually trademarked in order to protect the project integrity and defend against misuse (compare the Apache Logo, Tux, etc.). This probably isn't the ideal place to discuss these legal fineries, though; the Dogecoin Foundation has been trying to figure out an ideal course of action (because we've had to work towards amicably resolving the "Doge"-Trademark application by UltraPro, anyway)

Anyway, to cut this short: the logo(s) should be excluded from a license change for now.

As for the license used for the code, I would advise to use CC because it is relatively well suited to license mixed website contents under; you could license the code differently (e. g. under MIT or WTFPL), but I don't see why that would be sensible in our specific case.

**Comment by jwiechers** [comment]
On that subject, after looking through it: would prefer it this doesn't get merged as is, but after a slight rewrite to make a few things more clear. :)

**Comment by dhpollack** [comment]
@jwiechers any suggestions on how to rewrite this to make it clearer?

**Comment by jwiechers** [comment]
Sure. Sorry. Other things kind of piled on and I pushed my reply here down my todo list. Will reply later today or tomorrow.

Jens

Sent from Samsung Mobile

-------- Original message --------

**Pull request closed without merging**
