### PR TITLE
community - small edit

### PR DESCRIPTION
**Pull request by leuqarte**
hide forum link, /r/dogecoin link text changed

### CODE REVIEW

**Comment by peoplma** [comment]
What happened to the dogecoin.com forum?

**Comment by leuqarte** [comment]
I get 404 error

**Comment by peoplma** [comment]
yeah me too :)  Just wondering what happened to it, why it's gone.  Too much spam probably.

Anyway:

ACK

**Comment by PowerLemons** [comment]
The issues that this PR fixes were resolved in [commit #273](https://github.com/dogecoin/dogecoin.com/commit/c929088b5b60d015193925660df9214f4a971149). Thanks for bringing up these issues nonetheless!

On line 248 with the change from "data-i18n="dogecoincom-reddit"" to "data-i18n="/r/dogecoin"" in your PR, that attribute is actually for the localization file (and not for the text itself). "dogecoincom-reddit" was the link itself in the Community modal because the localization "dogecoincom-reddit" in the attribute did not actually exist. This was changed to "dgc-reddit", as it seems that was the intended value.

**Pull request closed without merging**
