### PR TITLE
Russian Translation

### PR DESCRIPTION
**Pull request by vonkoro**
### Description
Added ru.json. Configured script.js so it will work with it. Added "Русский" option to index.html, guide.html, support.html. Fixed a typo in de.json and fr.json, that were the cause of a bug when languages didn't wanna switch.

### Motivation and Context
There's a lotta russians who don't know english. This might help them start using Dogecoin.

### How Has This Been Tested?
Works great on my laptop.

### CODE REVIEW

**Comment by drushadrusha** [comment]
It looks like machine translation in some places. 
Do you mind if I contribute?

**Comment by vonkoro** [comment]
> It looks like machine translation in some places. 
> Do you mind if I contribute? 

Would be great!

**Comment by drushadrusha** [comment]
I made a pull request to your fork with some fixes.

**Review by langerhans — APPROVED** [review]
Looking good to me. Thanks a lot!

**Pull request merged**
