### PR TITLE
Replaces MyDoge with Dogekeeper

### PR DESCRIPTION
**Pull request by DomT4**
Replaces the current non-wallet link with [Dogekeeper](https://itunes.apple.com/app/dogekeeper/id889806231), which can be used to send and receive Dogecoins thanks to the DogeAPI service.

### CODE REVIEW

**Comment by PowerLemons** [comment]
Even though DogeKeeper is an actual wallet compared to MyDoge, my main concern about DogeKeeper is the code - it isn't open-source.

MyDoge isn't too, but it's just a Dogecoin wallet viewer. This app on the other-hand signs into your DogeAPI account and can make transactions on it. There is too much potential for the app developer to steal people's account information and their coins unless the code is out there for everyone to review. Not saying the app developer will definitely do this, but it's a possibility.

I've contacted the app developer if he could possibly make the code open-source, but he has not gotten back to me yet.

**Comment by DomT4** [comment]
Understandable. It's a concern I've had with these things as well.

I've reached out to quite a few devs who have pushed wallets out there, even those who have pushed open-source wallets out there but most have been resistant to the idea of open-sourcing the actual iOS element because of fears that someone could just take the code, insert something malicious and then submit the app to Apple and have people diverted from the intended app to something more malicious.

Whether that fear is entirely understandable depends I guess on how much folks trust Apple to act as a gatekeeper over the App Store and stop anything like this from happening. It's uncharted waters as far as cryptocurrencies go.

**Comment by PowerLemons** [comment]
That's understandable. If the app developer does not wish to make it open-source, maybe one of Dogecoin's trusted developers could take a look at the code instead.

**Comment by DomT4** [comment]
That'd be an acceptable compromise. I know Langers is Android, but he'd probably be able to take a look through the code if the idea was acceptable to the developer.

**Comment by Andrew-Dev** [comment]
I am the developer of Dogekeeper. I am considering open source as a possibility, but there are still risks I worry about with open source. I am willing to let a Dogecoin trusted developer look at the code if they would like.

**Comment by DomT4** [comment]
@langerhans, Anything you can do for the above?

**Comment by Andrew-Dev** [comment]
I made it open source. https://github.com/Andrew-Dev/DogeKeeper

**Comment by langerhans** [comment]
I have no idea about Objective-C. Someone else has to look over it.

**Comment by DomT4** [comment]
Darn. I know a _tiny bit_ of Obj-C, but not enough to authoritatively look over an entire source code and say one way or another that something definitely is or isn't safe. Is there anyone on the team who knows Obj-C?

**Comment by DomT4** [comment]
@Andrew-Dev - Thanks! That's actually incredibly decent of you to do so. If you'd prefer to narrow your risk when it comes to anyone taking, modifying & re-using the code you could always use [this](https://creativecommons.org/licenses/by-nc-nd/4.0/) CC license instead which bars deriv works and should offer you a slightly higher degree of protection.

I'll see if I can hunt anyone down who knows Obj-C well enough to go through it. I'll take a glance, but as I said, Obj-C is definitely not my strong point right now.

**Comment by Andrew-Dev** [comment]
I may use that CC license instead now that I think about that because there may be too many risks with allowing others to create derivatives of my code. Even with the current ShareAlike license that I have.

**Comment by DomT4** [comment]
It's probably a pretty good step for now to adopt deriv-restrictive licensing until the time comes when there's less potential for maliciousness by less honest individuals around.

You probably want to update your README to reflect the change as well. It still echos the old license at the moment.

My thanks once again for posting the code. I'll try and find someone trustworthy to go through it ASAP.

**Comment by Andrew-Dev** [comment]
I updated the license in all of the file headers, LICENSE.md and the README.
For anybody who wants to go through it, DogeAPIHandler.m is where everything regarding DogeAPI is done.

**Comment by PowerLemons** [comment]
Does this application still work? I'm considering on merging it because it's been out for so long without any problems from what I know.

**Comment by Andrew-Dev** [comment]
Yes it still works, although it uses Block.io instead of DogeAPI.

**Comment by DomT4** [comment]
Yeah, it works fine. I took a look over the source code, and although Obj-C isn't really my thing at all I didn't spot anything funky or odd. Without being able to find anyone with more Obj-C experience, I'm giving this as much of a thumbs up as I can.

**Comment by PowerLemons** [comment]
DogeKeeper has replaced MyDoge in a commit. Closing this PR.

**Pull request closed without merging**
