### PR TITLE
Added v Shibe

### PR DESCRIPTION
**Pull request by whitj00**
Added shibe because shibe is wow

### CODE REVIEW

**Comment by whitj00** [comment]
Also removed my doge

**Comment by ummjackson** [comment]
Why should MYDOGE be removed?

**Comment by whitj00** [comment]
It's a great app, but it just isn't a wallet.  There should be a seperate category for it.

**Comment by ummjackson** [comment]
It's the closest we're going to get to a wallet on an Apple device, so I don't see a justification for removing it. Tricky one to make a call on, but don't want to exclude the iPhone users.

**Pull request closed without merging**
