### PR TITLE
Complete Redesign

### PR DESCRIPTION
**Pull request by PowerLemons**
A complete redesign for Dogecoin.com.
It is modern, simple, and informative. It also has an interactive Getting Started guide.
This redesign passes the W3C Validator, and it is also completely responsive.

Preview can be found here: http://doge-coins.us/

### CODE REVIEW

**Comment by langerhans** [comment]
Hi there, I'm sorry that you didn't receive a reply yet. Silly Github didn't notify me :/ I'll give this a deeper look soon. Just stopping by to say that.

**Comment by PowerLemons** [comment]
Thanks, was a bit worried because no one replied to this for 3 days!

**Comment by ummjackson** [comment]
[Edit]:

I'd previously written a long response, but after some reflection am going to merge this and then iterate on it with my feedback. Thanks again for doing this, really appreciated.

**Comment by ummjackson** [comment]
Merged and tweaked. 
- Removed space background - the team weren't sure about this, neither was I. We can put it to a vote later, but for now we're going with the tried/true simple background. 
- Updated doge picture to use the official design by Christine Ricks (which she's fine with us using from a license perspective as well)
- Tweaked the copy flow and messaging, should read a little smoother now. 

Thanks again @PowerLemons - really appreciated :+1:

**Comment by PowerLemons** [comment]
No problem, thank you for doing this =)

**Pull request merged**
