### PR TITLE
add language flag buttons on index.html

### PR DESCRIPTION
**Pull request by joshuahonig**
added language flags, english, french, doge, couldn't find german translation of dogecoin.com

### CODE REVIEW

**Comment by patricklodder** [comment]
German: `http://dogecoin.com/?lng=de`
Spanish: `http://dogecoin.com/?lng=es`

Could you please use public domain / open source flag images and add those to your pull request (in `imgs/`) instead of deeplinking other sites?

**Comment by joshuahonig** [comment]
I'll add German and Spanish. And I'll get working on new flags, but the site I linked to was mine and I don't plan on seeing it go. If possible, could I give you the file and you upload it to dogecoin.com so it can link to itself?

(also, sorry if I'm doing this wrong. I'm brand new to github)

**Comment by patricklodder** [comment]
I think we can best grab Public Domain flag images from here: http://www.wpclipart.com/flags/index.html (it's listed on wikipedia as a PD image source and it says `public domain clip art` on the header) 

I'll try to find some time this weekend to help you with your pull request and to get everything in order, if @peoplma doesn't beat me to it, that is :D

**Comment by patricklodder** [comment]
closing this. if anyone wants the flags back, please make a new PR.

**Pull request closed without merging**
