### PR TITLE
BENGALI TRANSLATION 

### LINKED ISSUE #242: CREATE A BANGLA TRANSLATION
### Use Case(s)
This change is required to reach the wider user base.

### PR DESCRIPTION
**Pull request by adityagi02**
Fixes #242 

**### ADDED BANGLA LANGUAGE TRANSLATION** 
### Motivation and Context
This change is required to reach the wider user base. 

### How Has This Been Tested?
Followed instruction from [MacOS Guide](https://github.com/dogecoin/dogecoin.com/blob/gh-pages/getting-started/contribute_osx.md)  

### Checklist:

- [x] GitHub issue linked
Fixes #242 
- [x] The necessary translations have been added for all languages
- [x] Any documentation has been updated accordingly
- [ ] _Responsive_ sizes (Mobile) tested
- [x] Cross Browser tested if necessary
- [ ] Conflicts resolved

### CODE REVIEW

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
I think for Bangla, the language code reference should be `bn` because `bg` is for Bulgarian

**Comment by adityagi02** [comment]
> I think for Bangla, the language code reference should be `bn` because `bg` is for Bulgarian

sure ,I'll work on this 👍

**Comment by sagormolla** [comment]
Hi

**Comment by sagormolla** [comment]
Can you help with this job ?

**Pull request closed without merging**
