### PR TITLE
Change DogeAPI to Block.io

### PR DESCRIPTION
**Pull request by Kirvx**
I added Block.io instead of DogeAPI in Getting Started (images, description + french description).
I'm not a web developper but i think it's ok....
Maybe you can correct few things and correct my english translations, since I'm french...

### CODE REVIEW

**Comment by dhpollack** [comment]
@Kirvx I think you didn't update your tree correctly before making the branch.  Specifically, commit [0a180e7](https://github.com/Kirvx/dogecoin.com/commit/0a180e7cb05baf5c2a66092dc5664f20c3e783c3) looks like it was behind the dogecoin.com gh-pages branch.  I think what you wanted to do was pull the remote to your local branch and then make your pull request branch from that.

To update your local branch with a remote see the [stackexchange answer here](http://stackoverflow.com/questions/9210446/replace-local-branch-with-remote-branch-entirely).

although now that you've already made the pull request, I'm not exactly sure how to fix this.

**Comment by Kirvx** [comment]
I'm a huge noob with Github.
I saw this problem but I thought it's was not important because 0a180e7 don't change what i want (in "Files changed") for this update, no?

**Comment by Kirvx** [comment]
Ok i will open a new pull request, if I can ^^

**Comment by dhpollack** [comment]
@Kirvx I'm only half a step ahead of you with this.  The first time I tried to get involved with a project, it was fairly big.  Long story short, I did [the exact same thing.](https://github.com/edx/configuration/pull/1118), but the guys were pretty helpful and walked me thru it.

**Pull request closed without merging**
