### PR TITLE
Fixed Grammer & Buttons

### PR DESCRIPTION
**Pull request by NeilShah2026**
### Description
I fixed the button stylings, as some were filled in, and others were not. I also fixed some grammar problems.

### Motivation and Context
Makes the website look more appealing.

### CODE REVIEW

**Comment by langerhans** [comment]
This would need to be rebased.

**Comment by NeilShah2026** [comment]
what do you mean?

**Comment by langerhans** [comment]
There are conflicts so this can't be merged right now. It's because the page had been updated after you made your changes. Also I'd argue "Language" is correct for a language selection :)

**Comment by zriyansh** [comment]
@NeilShah2026 update your fork to rebase and then open a merge request. 
Thank you

**Comment by NeilShah2026** [comment]
Ok

**Review by EverythingWillBeCode — APPROVED** [review]

**Comment by EverythingWillBeCode** [comment]
Good Job!

**Comment by NeilShah2026** [comment]
This is already merged

**Pull request closed without merging**
