### PR TITLE
Request to change the dogecoin.com Header/Footer/Text colors from navy/dark blue to black. 

### PR DESCRIPTION
**Pull request by bobbobobbo**
### Description
I apologize if this request is in the wrong area or wrong style!
As shown in this thread, there are 65+ upvotes in support of this change (which is a lot for this subreddit)
https://old.reddit.com/r/dogecoindev/comments/ml4az8/our_website_would_look_really_great_in_offblack/

I know the original palette was used, but navy blue wasn't really a focus before, and black or off-black would look really sharp. (the website itself is really clean in general though!)

### Motivation and Context
It would give the website a really clean/professional look.

### How Has This Been Tested?
Tested only via image mock-up. I do not have the code experience (at least in this language).

### Screenshots (if appropriate):
Example shown here!:  https://ibb.co/0XJX7T1

### CODE REVIEW

**Comment by patricklodder** [comment]
Hey! I don't think the change is in here? At least I cannot find it?

I'll work a bit on the contribution guides to make it easier for people to understand the process. In the meantime, this is what you want to do:

1. Click the fork button at the top to make a local copy of this repository.
2. Make your edits to the CSS on your repository and update it
3. Do a pull request back with your edits
4. We restart this discussion :-)

**Comment by bobbobobbo** [comment]
My mistake. I have limited experience with CSS, I was confused on some things I thought I could make a request and someone else would potentially jump in (or the gentleman that re-edited the site) could see this and do so. Yet I see this is the last step, with a finished product to request. I suppose I'm out of luck, my mistake! Yet thank you for being understanding and if there's any traction or can forward to the original editor for him to review, it would be appreciated. Cheers.

**Comment by patricklodder** [comment]
No problem. How did you get the images like they are?

**Comment by bobbobobbo** [comment]
A quick mock up in GIMP/Photoshop.

**Pull request closed without merging**
